# Generated by Django 2.0 on 2018-11-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pants',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shirts',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='status',
        ),
        migrations.AddField(
            model_name='pants',
            name='weather',
            field=models.CharField(choices=[('WARM', 'This piece of clothing can be worn in colder temperatures'), ('MEDIUM', 'This piece of clothing can be worn in any temperature'), ('COOL', 'This piece of clothing can be worn in warmer temperatures')], default='SOLD', max_length=10),
        ),
        migrations.AddField(
            model_name='shirts',
            name='weather',
            field=models.CharField(choices=[('WARM', 'This piece of clothing can be worn in colder temperatures'), ('MEDIUM', 'This piece of clothing can be worn in any temperature'), ('COOL', 'This piece of clothing can be worn in warmer temperatures')], default='SOLD', max_length=10),
        ),
        migrations.AddField(
            model_name='shoes',
            name='weather',
            field=models.CharField(choices=[('WARM', 'This piece of clothing can be worn in colder temperatures'), ('MEDIUM', 'This piece of clothing can be worn in any temperature'), ('COOL', 'This piece of clothing can be worn in warmer temperatures')], default='SOLD', max_length=10),
        ),
    ]
