# Generated by Django 2.0 on 2018-11-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_auto_20181129_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pants',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='shirts',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='issues',
        ),
    ]
